apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  PGDATA: "/data/pgdata"